#!/usr/bin/env bash
# Generate swift/Sources/FendCommon/RuntimeManifest.swift with the version,
# bundle name, and SHA256 baked in. Called by release.yml during the macOS
# build job, before `swift build`, so the notarized binary already knows
# exactly which tarball to fetch and exactly what to verify it against.

set -euo pipefail

VERSION=""
BUNDLE=""
SHA256=""
OUTPUT=""

usage() {
    cat <<'EOF'
usage: ./scripts/write-runtime-manifest.sh [options]

options:
  --version VERSION    Fend version, no leading v (e.g. 0.1.0-alpha.3).
  --bundle FILENAME    Bundle filename uploaded to the GH Release.
  --sha256 HEX         SHA256 of the bundle (64 hex chars).
  --output PATH        Path of the generated Swift file.
  -h, --help           Show this help.
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --version) VERSION="${2:-}"; shift 2 ;;
        --bundle) BUNDLE="${2:-}"; shift 2 ;;
        --sha256) SHA256="${2:-}"; shift 2 ;;
        --output) OUTPUT="${2:-}"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "fend: unknown option: $1" >&2; usage >&2; exit 1 ;;
    esac
done

for var in VERSION BUNDLE SHA256 OUTPUT; do
    if [ -z "${!var}" ]; then
        echo "fend: --${var,,} is required" >&2
        exit 1
    fi
done

if ! [[ "$SHA256" =~ ^[a-f0-9]{64}$ ]]; then
    echo "fend: --sha256 must be 64 lowercase hex chars, got: $SHA256" >&2
    exit 1
fi

OWNER_REPO="${FEND_RELEASE_OWNER_REPO:-Lisovate/fend}"
URL="https://github.com/${OWNER_REPO}/releases/download/v${VERSION}/${BUNDLE}"

mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<EOF
// Generated by scripts/write-runtime-manifest.sh during release.yml.
// Do not edit by hand. The SHA256 is the hash of the runtime bundle
// published as a release asset alongside this binary, baked in at
// build time so first-run verification needs no out-of-band trust.

public enum RuntimeManifest {
    public static let runtimeVersion: String = "${VERSION}"
    public static let bundleName: String = "${BUNDLE}"
    public static let bundleSHA256: String = "${SHA256}"
    public static let bundleURL: String = "${URL}"
    public static let schemaVersion: Int = 1
}
EOF

echo "fend: wrote $OUTPUT"
echo "  version: $VERSION"
echo "  bundle:  $BUNDLE"
echo "  sha256:  $SHA256"
echo "  url:     $URL"
